export enum ACTION_TYPE {
  SET_DATA_TRANSACTION = 'SET_DATA_TRANSACTION',
  SET_DATA_CHECKOUT = 'SET_DATA_CHECKOUT',
  SET_DATA_NOTIFICATION = 'SET_DATA_NOTIFICATION',
  SET_DATA_HISTORY_TRANSACTION = 'SET_DATA_HISTORY_TRANSACTION',
  SET_TOGGLE_SIDEBAR = 'SET_TOGGLE_SIDEBAR',
}